module.exports = {
  Account: require("./Account"),
  ActivityLog: require("./ActivityLog"),
  BusinessSettings: require("./BusinessSettings"),
  Counter: require("./Counter"),
  Customer: require("./Customer"),
  Expense: require("./Expense"),
  Income: require("./Income"),
  Notification: require("./Notification"),
  Order: require("./Order"),
  Payment: require("./Payment"),
  Product: require("./Product"),
  Purchase: require("./Purchase"),
  Return: require("./Return"),
  Sale: require("./Sale"),
  StockMovement: require("./StockMovement"),
  Supplier: require("./Supplier"),
  Target: require("./Target"),
  User: require("./User"),
};